ALTER TABLE attacks ADD COLUMN killed INTEGER NOT NULL DEFAULT 0;
ALTER TABLE attacks ADD COLUMN injured INTEGER NOT NULL DEFAULT 0;
ALTER TABLE attacks ADD COLUMN casualty_status TEXT NOT NULL DEFAULT 'reported';
